# Generated by Django 2.2 on 2020-01-07 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='active',
            new_name='c_active',
        ),
    ]
