# Generated by Django 2.2 on 2020-01-08 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20200108_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_per',
            new_name='discount_percentage',
        ),
    ]
