# Generated by Django 2.2 on 2020-01-08 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20200108_1129'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.Coupon'),
        ),
    ]
