# Generated by Django 2.2 on 2020-01-07 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='active',
            new_name='p_active',
        ),
    ]
